image: gradle:7.2.0-jdk8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .gradle
    - ~/.gradle


build:
  stage: build
  script:
    - rm -rf build
    - gradle :free:shadowJar
  artifacts:
    paths:
      - free/build/libs

pages:
  stage: build
  image: gradle:6.8.3-jdk15
  only:
    - master
  script:
    - gradle :api:javadoc
    - mv api/build/docs/javadoc public
  artifacts:
    paths:
      - public

test:
  stage: test
  dependencies:
    - build
  script:
    - gradle :free:test

deploy to maven repo:
  stage: deploy
  only:
    - master
  dependencies:
    - build
  script:
    - gradle :api:publish --stacktrace
    - gradle :common:publish

upload to updater:
  stage: deploy
  only:
    - master
  dependencies:
    - build
  script:
    - cd free/build/libs
    - files=(*)
    - curl -i -F "submit=true" -F "secret=$UPLOAD_SECRET" -F "file=@${files[0]}" https://ajg0702.us/pl/updater/upload.php
