# Dont touch this number please
config-version: 11

# The time the server will wait between sending people in the queue
#  Default: 5
wait-time: 5

# The time that a server has to be offline to be marked as offline instead of restarting
#  Default: 120
offline-time: 120

# The time the server will wait between sending players update messages on what position they are in the queue.
# Default: 10
message-time: 10

# If a player is in a server, you can have the plugin make them automatically join a queue for another server
# Example with the default values: Player joins survivalqueue server, they will auto-join the queue for survival
queue-servers:
- 'survivalqueue:survival'

# Should the plugin send an actionbar to the player?
# Requires this plugin to be installed on the server the player is on for it to work
send-actionbar: true

# What kick reasons should cause the player to be removed from the queue?
# For example, if one of the below kick reasons is 'banned' and the player gets kicked when trying to connect to
#  a server in a queue with a message saying "You are banned from this server!" then it will kick them from the queue too.
kick-reasons:
- 'banned'
- 'blacklisted'


# Should we remove a player from the queue if they move servers?
# If they join another queue, they will be removed from the previous one no matter what
# This is more meant for if you have multiple lobbies if you want to let the player switch
# between them without losing their queue position
#  Default: true
remove-player-on-server-switch: true


# Should we wait until the server is done loading to load the servers?
# Enable this if you have a plugin that adds servers to the server list during startup.
#  Default: false
wait-to-load-servers: false

# How long should we wait after the server finishes loading to load the server list?
# Only works if the above is enabled.
# This is in miliseconds so 1000 = 1 second
#  Default: 500
wait-to-load-servers-delay: 500


# How often (in seconds) we should check for new servers to add queues for.
# If you dynamicly add servers, set this to something other than 0.
# To disable, set to 0
reload-servers-interval: 0


# Should we require permissions for players to be able to join queues?
# If enabled, players will be required to have the permission ajqueue.queue.<server>
#  Default: false
require-permission: false


# Should we let players join more than one queue?
# If enabled, players will be able to be in multiple queues at once.
#  Default: true
allow-multiple-queues: true

# If the player is queued for multiple servers, which server should we pick to use in things like placeholders and actionbars
# Options are first and last
#  Default: last
multi-server-queue-pick: last


# THIS FEATURE IS ONLY AVAILABLE ON ajQueuePlus (https://www.spigotmc.org/resources/ajqueueplus.79123/)
# This will show players a different name than the actual bungeecord server name
# for example, instead of showing players "event-a", this option can make it appear as "Event A"
# With this example, you would use this: - "event-a:Event A"
# Note that currently players still have to use the normal names in queue commands and leave commands
server-aliases:
- "event-a:Event A"


# How long should we wait after a server is online before sending players?
# The server will still show up as offline or restarting until this amount of time after its up
# Meant to let your server 'cool down' after lag from starting up
# In seconds
#  Default: 1
wait-after-online: 1
