# Dont touch this number please
config-version: 5

# The time the server will wait between sending people in the queue
#  Default: 5
wait-time: 5

# The time that a server has to be offline to be marked as offline instead of restarting
#  Default: 120
offline-time: 120

# The time the server will wait between sending players update messages on what position they are in the queue.
# Default: 10
message-time: 10

# If a player is in a server, you can have the plugin make them automatically join a queue for another server
# Example with the default values: Player joins survivalqueue server, they will auto-join the queue for survival
queue-servers:
- 'survivalqueue:survival'

# Should the plugin send an actionbar to the player?
# Requires this plugin to be installed on the server the player is on for it to work
send-actionbar: true

# What kick reasons should cause the player to be removed from the queue?
# For example, if one of the below kick-reasons is 'banned' and the player gets kicked when trying to connect to
#  a server in a queue with a message saying "You are banned from this server!" then it will kick them from the queue too.
kick-reasons:
- 'banned'
- 'blacklisted'


# Should we remove a player from the queue if they move servers?
# If they join another queue, they will be removed from the previous one no matter what
# This is more meant for if you have multiple lobbies if you want to let the player switch
# between them without losing their queue position
#  Default: true
remove-player-on-server-switch: true