main: us.ajg0702.queue.spigot.Main
version: "@VERSION@"
api-version: 1.13
author: ajgeiss0702
name: ajQueue
softdepend: [PlaceholderAPI]
commands:
   move:
      aliases: [server, queue, joinq, joinqueue]
      description: Queue for a server
   leavequeue:
      aliases: [leaveq]
      description: Leaves a queue